apiVersion: v1
kind: Pod
metadata:
  name: <name-of-pod-to-attach-to>
spec:
  containers:
    - name: my-container
      image: my-image
      volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/nfs
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: CORE-Kuber1