apiVersion: v1
kind: PersistentVolume
metadata:
  name: CORE-Kuber
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.2
    path: /volume1/CORE-Kuber1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: CORE-Kuber1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      type: nfs
      name: CORE-Kuber