apiVersion: v1
kind: Pod
metadata:
  name: pihole
  namespace: infrastructure
spec:
  hostNetwork: true
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      # upstream DNS used by pihole.
      - 192.168.0.254
  containers:
    - name: pihole
      # https://hub.docker.com/r/pihole/pihole/tags
      image: pihole/pihole:2021.10
      imagePullPolicy: IfNotPresent
      env:
        - name: TZ
          value: "Europe/Warsaw"
        - name: WEBPASSWORD
          value: Bogolino1!
      securityContext:
        privileged: true
      ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 67
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
      volumeMounts:
        - name: etc
          mountPath: /etc/pihole
        - name: dnsmasq
          mountPath: /etc/dnsmasq.d

  volumes:
    - name: etc
      persistentVolumeClaim:
        claimName: pihole-etc-pvc
    - name: dnsmasq
      persistentVolumeClaim:
        claimName: pihole-dnsmasq-pvc
